using MyWeather.Models;

namespace MyWeather.Services;

/// <summary>
/// Mock weather service with seasonal 48-hour scenarios typical for Örebro/central Sweden.
/// </summary>
public class MockWeatherService : IWeatherService
{
    private readonly IConfiguration _configuration;

    public MockWeatherService(IConfiguration configuration)
    {
        _configuration = configuration;
    }

    public Task<List<HourlyForecast>> GetForecastsAsync(double latitude, double longitude)
    {
        var month = _configuration.GetValue<int?>("Weather:MockMonth") ?? DateTime.Now.Month;
        var forecasts = GetSeasonalForecasts(month);
        return Task.FromResult(forecasts);
    }

    private static List<HourlyForecast> GetSeasonalForecasts(int month) => month switch
    {
        // January: Kall vinterdag, klart på morgonen, snö på eftermiddagen → dag 2 klart och kallt
        1 => [
            new(0, -12, WeatherCondition.Clear, 2, "clearsky_night"),
            new(2, -14, WeatherCondition.Clear, 1, "clearsky_night"),
            new(4, -15, WeatherCondition.Clear, 1, "clearsky_night"),
            new(6, -14, WeatherCondition.Clear, 2, "clearsky_night"),
            new(8, -10, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(10, -7, WeatherCondition.Cloudy, 3, "cloudy"),
            new(12, -5, WeatherCondition.Snow, 4, "snow", 1.2f),
            new(14, -4, WeatherCondition.Snow, 4, "snow", 1.5f),
            new(16, -6, WeatherCondition.Snow, 3, "lightsnow", 0.8f),
            new(18, -8, WeatherCondition.Cloudy, 2, "cloudy"),
            new(20, -10, WeatherCondition.PartlyCloudy, 2, "partlycloudy_night"),
            new(22, -11, WeatherCondition.Clear, 1, "clearsky_night"),
            new(24, -13, WeatherCondition.Clear, 1, "clearsky_night"),
            new(26, -14, WeatherCondition.Clear, 1, "clearsky_night"),
            new(28, -15, WeatherCondition.Clear, 1, "clearsky_night"),
            new(30, -14, WeatherCondition.Clear, 2, "clearsky_night"),
            new(32, -11, WeatherCondition.Clear, 2, "clearsky_day"),
            new(34, -8, WeatherCondition.Clear, 2, "clearsky_day"),
            new(36, -6, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(38, -5, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(40, -7, WeatherCondition.Clear, 2, "clearsky_day"),
            new(42, -9, WeatherCondition.Clear, 2, "clearsky_night"),
            new(44, -11, WeatherCondition.Clear, 1, "clearsky_night"),
            new(46, -12, WeatherCondition.Clear, 1, "clearsky_night"),
            new(48, -13, WeatherCondition.Clear, 1, "clearsky_night"),
        ],

        // February: Kall men solig → dag 2 molnigt
        2 => [
            new(0, -8, WeatherCondition.Clear, 2, "clearsky_night"),
            new(2, -10, WeatherCondition.Clear, 1, "clearsky_night"),
            new(4, -11, WeatherCondition.Clear, 1, "clearsky_night"),
            new(6, -9, WeatherCondition.Clear, 2, "clearsky_night"),
            new(8, -5, WeatherCondition.Clear, 2, "clearsky_day"),
            new(10, -2, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(12, 0, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(14, 1, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(16, -1, WeatherCondition.Clear, 2, "clearsky_day"),
            new(18, -4, WeatherCondition.Clear, 2, "clearsky_night"),
            new(20, -6, WeatherCondition.Clear, 1, "clearsky_night"),
            new(22, -7, WeatherCondition.Clear, 1, "clearsky_night"),
            new(24, -9, WeatherCondition.Clear, 1, "clearsky_night"),
            new(26, -10, WeatherCondition.Cloudy, 2, "cloudy"),
            new(28, -10, WeatherCondition.Cloudy, 2, "cloudy"),
            new(30, -8, WeatherCondition.Cloudy, 3, "cloudy"),
            new(32, -5, WeatherCondition.Cloudy, 3, "cloudy"),
            new(34, -3, WeatherCondition.Cloudy, 3, "cloudy"),
            new(36, -2, WeatherCondition.Snow, 4, "lightsnow", 0.5f),
            new(38, -2, WeatherCondition.Snow, 4, "snow", 1.0f),
            new(40, -3, WeatherCondition.Cloudy, 3, "cloudy"),
            new(42, -5, WeatherCondition.Cloudy, 2, "cloudy"),
            new(44, -6, WeatherCondition.Cloudy, 2, "cloudy"),
            new(46, -7, WeatherCondition.Cloudy, 2, "cloudy"),
            new(48, -8, WeatherCondition.Cloudy, 2, "cloudy"),
        ],

        // Mars: Vårvinter → dag 2 sol
        3 => [
            new(0, -3, WeatherCondition.Clear, 3, "clearsky_night"),
            new(2, -4, WeatherCondition.Clear, 2, "clearsky_night"),
            new(4, -4, WeatherCondition.Clear, 2, "clearsky_night"),
            new(6, -2, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(8, 1, WeatherCondition.PartlyCloudy, 4, "partlycloudy_day"),
            new(10, 4, WeatherCondition.PartlyCloudy, 4, "partlycloudy_day"),
            new(12, 6, WeatherCondition.PartlyCloudy, 5, "partlycloudy_day"),
            new(14, 7, WeatherCondition.Cloudy, 5, "cloudy"),
            new(16, 5, WeatherCondition.Cloudy, 4, "cloudy"),
            new(18, 2, WeatherCondition.PartlyCloudy, 3, "partlycloudy_night"),
            new(20, 0, WeatherCondition.Clear, 2, "clearsky_night"),
            new(22, -1, WeatherCondition.Clear, 2, "clearsky_night"),
            new(24, -2, WeatherCondition.Clear, 2, "clearsky_night"),
            new(26, -3, WeatherCondition.Clear, 1, "clearsky_night"),
            new(28, -3, WeatherCondition.Clear, 1, "clearsky_night"),
            new(30, -1, WeatherCondition.Clear, 2, "clearsky_day"),
            new(32, 2, WeatherCondition.Clear, 3, "clearsky_day"),
            new(34, 5, WeatherCondition.Clear, 3, "clearsky_day"),
            new(36, 8, WeatherCondition.Clear, 3, "clearsky_day"),
            new(38, 9, WeatherCondition.Clear, 3, "clearsky_day"),
            new(40, 7, WeatherCondition.Clear, 2, "clearsky_day"),
            new(42, 4, WeatherCondition.Clear, 2, "clearsky_night"),
            new(44, 2, WeatherCondition.Clear, 1, "clearsky_night"),
            new(46, 0, WeatherCondition.Clear, 1, "clearsky_night"),
            new(48, -1, WeatherCondition.Clear, 1, "clearsky_night"),
        ],

        // April: Vårdag med regnskurar → dag 2 uppklarnande
        4 => [
            new(0, 2, WeatherCondition.Cloudy, 4, "cloudy"),
            new(2, 1, WeatherCondition.Cloudy, 3, "cloudy"),
            new(4, 1, WeatherCondition.Cloudy, 3, "cloudy"),
            new(6, 3, WeatherCondition.PartlyCloudy, 4, "partlycloudy_day"),
            new(8, 6, WeatherCondition.PartlyCloudy, 5, "partlycloudy_day"),
            new(10, 9, WeatherCondition.Rain, 6, "rainshowers_day", 2.1f),
            new(12, 10, WeatherCondition.Rain, 6, "rain", 3.5f),
            new(14, 11, WeatherCondition.PartlyCloudy, 5, "partlycloudy_day"),
            new(16, 9, WeatherCondition.PartlyCloudy, 4, "partlycloudy_day"),
            new(18, 7, WeatherCondition.Cloudy, 3, "cloudy"),
            new(20, 5, WeatherCondition.Cloudy, 3, "cloudy"),
            new(22, 4, WeatherCondition.Cloudy, 2, "cloudy"),
            new(24, 3, WeatherCondition.Cloudy, 2, "cloudy"),
            new(26, 2, WeatherCondition.Cloudy, 2, "cloudy"),
            new(28, 2, WeatherCondition.Cloudy, 3, "cloudy"),
            new(30, 4, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(32, 7, WeatherCondition.PartlyCloudy, 4, "partlycloudy_day"),
            new(34, 10, WeatherCondition.Clear, 4, "clearsky_day"),
            new(36, 12, WeatherCondition.Clear, 3, "clearsky_day"),
            new(38, 13, WeatherCondition.Clear, 3, "clearsky_day"),
            new(40, 11, WeatherCondition.Clear, 2, "clearsky_day"),
            new(42, 8, WeatherCondition.Clear, 2, "clearsky_night"),
            new(44, 6, WeatherCondition.Clear, 1, "clearsky_night"),
            new(46, 5, WeatherCondition.Clear, 1, "clearsky_night"),
            new(48, 4, WeatherCondition.Clear, 1, "clearsky_night"),
        ],

        // Maj: Varm vårdag → dag 2 skurar
        5 => [
            new(0, 7, WeatherCondition.Clear, 2, "clearsky_night"),
            new(2, 5, WeatherCondition.Clear, 1, "clearsky_night"),
            new(4, 5, WeatherCondition.Clear, 1, "clearsky_night"),
            new(6, 8, WeatherCondition.Clear, 2, "clearsky_day"),
            new(8, 12, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(10, 16, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(12, 19, WeatherCondition.Clear, 3, "clearsky_day"),
            new(14, 20, WeatherCondition.Clear, 3, "clearsky_day"),
            new(16, 18, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(18, 15, WeatherCondition.PartlyCloudy, 2, "partlycloudy_night"),
            new(20, 12, WeatherCondition.Clear, 2, "clearsky_night"),
            new(22, 10, WeatherCondition.Clear, 1, "clearsky_night"),
            new(24, 8, WeatherCondition.Clear, 1, "clearsky_night"),
            new(26, 7, WeatherCondition.Clear, 1, "clearsky_night"),
            new(28, 7, WeatherCondition.Cloudy, 2, "cloudy"),
            new(30, 9, WeatherCondition.Cloudy, 3, "cloudy"),
            new(32, 12, WeatherCondition.Rain, 4, "lightrainshowers_day", 0.8f),
            new(34, 14, WeatherCondition.Rain, 5, "rainshowers_day", 2.5f),
            new(36, 15, WeatherCondition.Rain, 5, "rain", 4.0f),
            new(38, 14, WeatherCondition.Cloudy, 4, "cloudy", 0.3f),
            new(40, 12, WeatherCondition.Cloudy, 3, "cloudy"),
            new(42, 10, WeatherCondition.Cloudy, 2, "cloudy"),
            new(44, 9, WeatherCondition.Cloudy, 2, "cloudy"),
            new(46, 8, WeatherCondition.Cloudy, 2, "cloudy"),
            new(48, 7, WeatherCondition.Cloudy, 2, "cloudy"),
        ],

        // Juni: Sommardag med sol och moln → dag 2 fortsatt fint
        6 => [
            new(0, 12, WeatherCondition.Clear, 2, "clearsky_night"),
            new(2, 11, WeatherCondition.Clear, 1, "clearsky_night"),
            new(4, 11, WeatherCondition.Clear, 1, "clearsky_night"),
            new(6, 13, WeatherCondition.Clear, 2, "clearsky_day"),
            new(8, 17, WeatherCondition.PartlyCloudy, 2, "partlycloudy_day"),
            new(10, 20, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(12, 23, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(14, 24, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(16, 22, WeatherCondition.Cloudy, 3, "cloudy"),
            new(18, 19, WeatherCondition.PartlyCloudy, 2, "partlycloudy_night"),
            new(20, 16, WeatherCondition.Clear, 2, "clearsky_night"),
            new(22, 14, WeatherCondition.Clear, 1, "clearsky_night"),
            new(24, 13, WeatherCondition.Clear, 1, "clearsky_night"),
            new(26, 12, WeatherCondition.Clear, 1, "clearsky_night"),
            new(28, 12, WeatherCondition.Clear, 1, "clearsky_night"),
            new(30, 14, WeatherCondition.Clear, 2, "clearsky_day"),
            new(32, 18, WeatherCondition.Clear, 2, "clearsky_day"),
            new(34, 21, WeatherCondition.Clear, 3, "clearsky_day"),
            new(36, 24, WeatherCondition.Clear, 3, "clearsky_day"),
            new(38, 25, WeatherCondition.Clear, 3, "clearsky_day"),
            new(40, 23, WeatherCondition.PartlyCloudy, 2, "partlycloudy_day"),
            new(42, 20, WeatherCondition.Clear, 2, "clearsky_night"),
            new(44, 17, WeatherCondition.Clear, 1, "clearsky_night"),
            new(46, 15, WeatherCondition.Clear, 1, "clearsky_night"),
            new(48, 14, WeatherCondition.Clear, 1, "clearsky_night"),
        ],

        // Juli: Varm sommardag → dag 2 åskskurar
        7 => [
            new(0, 15, WeatherCondition.Clear, 1, "clearsky_night"),
            new(2, 14, WeatherCondition.Clear, 1, "clearsky_night"),
            new(4, 14, WeatherCondition.Clear, 1, "clearsky_night"),
            new(6, 16, WeatherCondition.Clear, 1, "clearsky_day"),
            new(8, 20, WeatherCondition.Clear, 2, "clearsky_day"),
            new(10, 24, WeatherCondition.Clear, 2, "clearsky_day"),
            new(12, 27, WeatherCondition.Clear, 2, "clearsky_day"),
            new(14, 28, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(16, 26, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(18, 23, WeatherCondition.Clear, 2, "clearsky_night"),
            new(20, 20, WeatherCondition.Clear, 1, "clearsky_night"),
            new(22, 17, WeatherCondition.Clear, 1, "clearsky_night"),
            new(24, 16, WeatherCondition.Clear, 1, "clearsky_night"),
            new(26, 15, WeatherCondition.Cloudy, 2, "cloudy"),
            new(28, 15, WeatherCondition.Cloudy, 2, "cloudy"),
            new(30, 17, WeatherCondition.Cloudy, 3, "cloudy"),
            new(32, 20, WeatherCondition.Cloudy, 4, "cloudy"),
            new(34, 22, WeatherCondition.Rain, 5, "rainshowersandthunder_day", 5.0f),
            new(36, 23, WeatherCondition.Rain, 6, "heavyrainandthunder", 8.0f),
            new(38, 21, WeatherCondition.Rain, 5, "rainshowers_day", 3.0f),
            new(40, 19, WeatherCondition.Cloudy, 3, "cloudy", 0.5f),
            new(42, 17, WeatherCondition.Cloudy, 2, "cloudy"),
            new(44, 16, WeatherCondition.PartlyCloudy, 2, "partlycloudy_night"),
            new(46, 15, WeatherCondition.Clear, 1, "clearsky_night"),
            new(48, 15, WeatherCondition.Clear, 1, "clearsky_night"),
        ],

        // Augusti: Sommardag med åskregn → dag 2 uppklarnande
        8 => [
            new(0, 14, WeatherCondition.Clear, 1, "clearsky_night"),
            new(2, 13, WeatherCondition.Clear, 1, "clearsky_night"),
            new(4, 12, WeatherCondition.Fog, 0, "fog"),
            new(6, 14, WeatherCondition.PartlyCloudy, 1, "partlycloudy_day"),
            new(8, 18, WeatherCondition.PartlyCloudy, 2, "partlycloudy_day"),
            new(10, 22, WeatherCondition.Cloudy, 3, "cloudy"),
            new(12, 24, WeatherCondition.Cloudy, 4, "cloudy"),
            new(14, 23, WeatherCondition.Rain, 6, "heavyrain", 6.0f),
            new(16, 20, WeatherCondition.Rain, 5, "rain", 3.5f),
            new(18, 18, WeatherCondition.Cloudy, 3, "cloudy", 0.5f),
            new(20, 16, WeatherCondition.PartlyCloudy, 2, "partlycloudy_night"),
            new(22, 15, WeatherCondition.Clear, 1, "clearsky_night"),
            new(24, 14, WeatherCondition.Clear, 1, "clearsky_night"),
            new(26, 13, WeatherCondition.Clear, 1, "clearsky_night"),
            new(28, 13, WeatherCondition.Clear, 1, "clearsky_night"),
            new(30, 15, WeatherCondition.Clear, 2, "clearsky_day"),
            new(32, 18, WeatherCondition.Clear, 2, "clearsky_day"),
            new(34, 21, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(36, 23, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(38, 22, WeatherCondition.PartlyCloudy, 3, "partlycloudy_day"),
            new(40, 20, WeatherCondition.Clear, 2, "clearsky_day"),
            new(42, 17, WeatherCondition.Clear, 2, "clearsky_night"),
            new(44, 15, WeatherCondition.Clear, 1, "clearsky_night"),
            new(46, 14, WeatherCondition.Clear, 1, "clearsky_night"),
            new(48, 13, WeatherCondition.Clear, 1, "clearsky_night"),
        ],

        // September: Tidig höst, svalt och mulet → dag 2 regn
        9 => [
            new(0, 8, WeatherCondition.Cloudy, 3, "cloudy"),
            new(2, 7, WeatherCondition.Cloudy, 3, "cloudy"),
            new(4, 6, WeatherCondition.Fog, 2, "fog"),
            new(6, 7, WeatherCondition.Fog, 2, "fog"),
            new(8, 9, WeatherCondition.Cloudy, 3, "cloudy"),
            new(10, 12, WeatherCondition.Cloudy, 4, "cloudy"),
            new(12, 14, WeatherCondition.PartlyCloudy, 4, "partlycloudy_day"),
            new(14, 14, WeatherCondition.PartlyCloudy, 4, "partlycloudy_day"),
            new(16, 12, WeatherCondition.Cloudy, 3, "cloudy"),
            new(18, 10, WeatherCondition.Cloudy, 3, "cloudy"),
            new(20, 9, WeatherCondition.Cloudy, 2, "cloudy"),
            new(22, 8, WeatherCondition.Cloudy, 2, "cloudy"),
            new(24, 8, WeatherCondition.Cloudy, 2, "cloudy"),
            new(26, 7, WeatherCondition.Cloudy, 3, "cloudy"),
            new(28, 7, WeatherCondition.Rain, 4, "lightrain", 0.5f),
            new(30, 8, WeatherCondition.Rain, 5, "rain", 1.8f),
            new(32, 9, WeatherCondition.Rain, 5, "rain", 2.5f),
            new(34, 10, WeatherCondition.Rain, 5, "rain", 2.0f),
            new(36, 10, WeatherCondition.Rain, 4, "lightrain", 1.0f),
            new(38, 9, WeatherCondition.Cloudy, 4, "cloudy", 0.3f),
            new(40, 8, WeatherCondition.Cloudy, 3, "cloudy"),
            new(42, 7, WeatherCondition.Cloudy, 3, "cloudy"),
            new(44, 7, WeatherCondition.Cloudy, 3, "cloudy"),
            new(46, 6, WeatherCondition.Cloudy, 2, "cloudy"),
            new(48, 6, WeatherCondition.Cloudy, 2, "cloudy"),
        ],

        // Oktober: Regnig höstdag → dag 2 fortsatt regn
        10 => [
            new(0, 5, WeatherCondition.Rain, 5, "rain", 1.5f),
            new(2, 5, WeatherCondition.Rain, 5, "rain", 1.2f),
            new(4, 4, WeatherCondition.Cloudy, 4, "cloudy"),
            new(6, 4, WeatherCondition.Cloudy, 5, "cloudy"),
            new(8, 5, WeatherCondition.Rain, 6, "rain", 2.5f),
            new(10, 7, WeatherCondition.Rain, 7, "heavyrain", 4.0f),
            new(12, 8, WeatherCondition.Rain, 6, "rain", 3.0f),
            new(14, 8, WeatherCondition.Cloudy, 5, "cloudy", 0.5f),
            new(16, 7, WeatherCondition.Cloudy, 5, "cloudy"),
            new(18, 6, WeatherCondition.Cloudy, 4, "cloudy"),
            new(20, 5, WeatherCondition.Cloudy, 4, "cloudy"),
            new(22, 5, WeatherCondition.Rain, 5, "lightrain", 0.8f),
            new(24, 4, WeatherCondition.Rain, 5, "rain", 1.5f),
            new(26, 4, WeatherCondition.Rain, 5, "rain", 2.0f),
            new(28, 4, WeatherCondition.Rain, 4, "lightrain", 1.0f),
            new(30, 5, WeatherCondition.Cloudy, 4, "cloudy", 0.3f),
            new(32, 6, WeatherCondition.Cloudy, 5, "cloudy"),
            new(34, 7, WeatherCondition.Rain, 6, "rainshowers_day", 2.0f),
            new(36, 7, WeatherCondition.Rain, 6, "rain", 3.5f),
            new(38, 6, WeatherCondition.Rain, 5, "lightrain", 1.5f),
            new(40, 5, WeatherCondition.Cloudy, 4, "cloudy"),
            new(42, 5, WeatherCondition.Cloudy, 4, "cloudy"),
            new(44, 4, WeatherCondition.Cloudy, 3, "cloudy"),
            new(46, 4, WeatherCondition.Cloudy, 3, "cloudy"),
            new(48, 3, WeatherCondition.Cloudy, 3, "cloudy"),
        ],

        // November: Grått och rått → dag 2 snöblandat regn
        11 => [
            new(0, 1, WeatherCondition.Cloudy, 4, "cloudy"),
            new(2, 0, WeatherCondition.Cloudy, 4, "cloudy"),
            new(4, 0, WeatherCondition.Fog, 3, "fog"),
            new(6, 0, WeatherCondition.Fog, 3, "fog"),
            new(8, 1, WeatherCondition.Cloudy, 4, "cloudy"),
            new(10, 3, WeatherCondition.Cloudy, 5, "cloudy"),
            new(12, 4, WeatherCondition.Rain, 5, "rain", 1.5f),
            new(14, 4, WeatherCondition.Rain, 5, "rain", 2.0f),
            new(16, 3, WeatherCondition.Cloudy, 4, "cloudy", 0.5f),
            new(18, 2, WeatherCondition.Cloudy, 4, "cloudy"),
            new(20, 1, WeatherCondition.Cloudy, 3, "cloudy"),
            new(22, 1, WeatherCondition.Cloudy, 3, "cloudy"),
            new(24, 0, WeatherCondition.Cloudy, 3, "cloudy"),
            new(26, -1, WeatherCondition.Cloudy, 4, "cloudy"),
            new(28, -1, WeatherCondition.Snow, 4, "sleet", 0.8f),
            new(30, 0, WeatherCondition.Rain, 5, "sleet", 1.5f),
            new(32, 1, WeatherCondition.Rain, 5, "lightrain", 1.0f),
            new(34, 2, WeatherCondition.Rain, 5, "rain", 2.0f),
            new(36, 2, WeatherCondition.Rain, 4, "lightrain", 1.0f),
            new(38, 1, WeatherCondition.Cloudy, 4, "cloudy"),
            new(40, 0, WeatherCondition.Cloudy, 3, "cloudy"),
            new(42, 0, WeatherCondition.Cloudy, 3, "cloudy"),
            new(44, -1, WeatherCondition.Cloudy, 3, "cloudy"),
            new(46, -1, WeatherCondition.Cloudy, 2, "cloudy"),
            new(48, -2, WeatherCondition.Cloudy, 2, "cloudy"),
        ],

        // December: Snöig vinterdag → dag 2 klart och kallt
        12 => [
            new(0, -5, WeatherCondition.Cloudy, 3, "cloudy"),
            new(2, -6, WeatherCondition.Cloudy, 3, "cloudy"),
            new(4, -7, WeatherCondition.Cloudy, 2, "cloudy"),
            new(6, -6, WeatherCondition.Snow, 3, "snow", 1.0f),
            new(8, -4, WeatherCondition.Snow, 4, "snow", 1.5f),
            new(10, -2, WeatherCondition.Snow, 4, "heavysnow", 2.5f),
            new(12, -1, WeatherCondition.Snow, 5, "heavysnow", 3.0f),
            new(14, -1, WeatherCondition.Cloudy, 4, "cloudy", 0.5f),
            new(16, -2, WeatherCondition.Cloudy, 3, "cloudy"),
            new(18, -4, WeatherCondition.Cloudy, 3, "cloudy"),
            new(20, -5, WeatherCondition.PartlyCloudy, 2, "partlycloudy_night"),
            new(22, -6, WeatherCondition.Clear, 2, "clearsky_night"),
            new(24, -7, WeatherCondition.Clear, 1, "clearsky_night"),
            new(26, -8, WeatherCondition.Clear, 1, "clearsky_night"),
            new(28, -9, WeatherCondition.Clear, 1, "clearsky_night"),
            new(30, -8, WeatherCondition.Clear, 1, "clearsky_day"),
            new(32, -6, WeatherCondition.Clear, 2, "clearsky_day"),
            new(34, -4, WeatherCondition.Clear, 2, "clearsky_day"),
            new(36, -3, WeatherCondition.Clear, 2, "clearsky_day"),
            new(38, -4, WeatherCondition.Clear, 2, "clearsky_day"),
            new(40, -6, WeatherCondition.Clear, 1, "clearsky_night"),
            new(42, -7, WeatherCondition.Clear, 1, "clearsky_night"),
            new(44, -8, WeatherCondition.Clear, 1, "clearsky_night"),
            new(46, -9, WeatherCondition.Clear, 1, "clearsky_night"),
            new(48, -10, WeatherCondition.Clear, 1, "clearsky_night"),
        ],

        _ => throw new ArgumentOutOfRangeException(nameof(month))
    };
}
